#!/usr/bin/env node
const Airtable = require('airtable');
const fetch = require('isomorphic-unfetch');
const path = require('path');
const fs = require('fs');
const util = require('util');
const accessPromise = util.promisify(fs.access);
const imageThumbnail = require('image-thumbnail');

const base = new Airtable({apiKey: process.env.AIRTABLE_API_KEY}).base(
  'appGVXX1d94zOm395',
);

base('FR Portfolio')
  .select({
    view: 'Grid view',
  })
  .all()
  .then(records => {
    const fields = records.map(record => record.fields);
    return Promise.all(
      fields.map(async p => {
        if (p['Eng Dwg'] == null && p['CAD'] == null) {
          return null;
        }
        await Promise.all(
          [
            // These are referenced records:
            //'Risk Assessment',
            //'Test Plan',
            //'FAI',
            //'BOM',
            'Maker Manual',
            'User Manual',
          ].map(async n => {
            const rec = p[n]?.[0];
            if (rec) {
              const record = await base('FR Portfolio').find(rec);
              p[n] = record.fields;
            }
          }),
        );
        const partNo = p['Part No.'];
        const images = await Promise.all(
          [
            ...p['Catalogue Image'],
            ...p['In use Image'],
            ...p['CAD Image'],
          ].map(async ({url, id}) => {
            const original = await makeThumbnail(
              partNo + '-' + id,
              url,
              400,
              300,
            );
            const projectCard = await makeThumbnail(
              partNo + '-' + id,
              url,
              290,
              200,
            );
            return {
              original,
              thumbnail: original,
              projectCard,
              fullscreen: url,
            };
          }),
        );
        return {...p, images};
      }),
    );
  })
  .then(projects => {
    projects = projects.filter(x => x);
    console.log(JSON.stringify(projects, null, 2));
  });

async function makeThumbnail(id, imageUrl, width, height) {
  if (!imageUrl) {
    return null;
  }

  const ext = path.extname(imageUrl).toLowerCase();
  const thumbnailUrl = `/images/${id}-${width}x${height}${ext}`;
  const imagePath = path.join('public', thumbnailUrl);

  const doesExist = await exists(imagePath);
  if (doesExist) {
    return thumbnailUrl;
  }

  const r = await fetch(imageUrl).catch(e => {
    console.warn('--------------------------------------------');
    console.warn(e);
    console.warn('--------------------------------------------');
    return null;
  });

  if (
    r.status != 200 ||
    !/^image\//.test(r.headers.get('Content-Type')) ||
    r.body == null
  ) {
    console.warn("Can't read image:", imageUrl);
    return null;
  } else {
    try {
      console.warn(imageUrl);
      const thumb = await imageThumbnail(r.body, {
        height,
        width,
        fit: 'cover',
      });
      await fs.promises.writeFile(imagePath, thumb);
    } catch (e) {
      console.warn('--------------------------------------------');
      console.warn(e);
      console.warn('............................................');
      console.warn("Can't write thumbnail for:", imageUrl);
      console.warn('--------------------------------------------');
      return null;
    }
  }
  return thumbnailUrl;
}

function exists(file) {
  return accessPromise(file, fs.constants.F_OK)
    .then(x => x == null)
    .catch(err => {
      if (err.code === 'ENOENT') {
        return false;
      } else {
        throw err;
      }
    });
}
